### ISSUE TITLE
Crashes in `SinglePropertyView` & Doesn't work fully in `DetailsView`

### ISSUE THREAD

**Issue by BenVlodgi** [unico-inc/AnyValuePluginDoc#1]
### Using an `AnyValue` with the `SinglePropertyView` will cause the editor to crash.
- This happens because `CustomizeChildren` isn't called for `SinglePropertyView`. *I don't know why exactly.*
- Then in `OnValueTypePicked` 
  - ```FNotifyHook* Hook = PropertyUtilities->GetNotifyHook();```
  - Crashes because `PropertyUtilities` is null because it normally is set in `CustomizeChildren`. 

### Using an `AnyValue` with the `DetailsView` does not show or allow editing of the Default Value.
![image](https://github.com/unico-inc/AnyValuePluginDoc/assets/1462374/22337d8c-c135-4ead-84ce-b24e8eed443f)

Ideally both of these would work for being able to edit an `AnyValue` in an editor widget using one of these reflection widgets.

**Comment by unico-git** [comment]
Thanks for reporting bugs!

> Using an `AnyValue` with the `SinglePropertyView` will cause the editor to crash

![image](https://github.com/unico-inc/AnyValuePluginDoc/assets/78710731/1bee414c-2ab9-4d42-b7e0-ed74f2715116)
The problem has been fixed in the latest version(1.1).
⚠️NOTE⚠️ Using an `AnyValue` with the `SinglePropertyView` will no longer cause the editor to crash but you cannot edit 
value of `AnyValue` with the `SinglePropertyView`. Please use `DetailsView` instead.

> Using an `AnyValue` with the `DetailsView` does not show or allow editing of the Default Value

![image](https://github.com/unico-inc/AnyValuePluginDoc/assets/78710731/8cb4b8b5-1f60-4d22-820d-e0f5d6f2dcce)
Default values will be displayed by clicking arrow button on the left side of the property label.
Please let me know if you can't see any buttons or edit values.

**Comment by BenVlodgi** [comment]
Thank you!
